
/* ---- Love Sound FX (Web Audio, no external files) ---- */
let soundOn=true,audioCtx=null;
const soundToggle=document.getElementById("soundToggle");
function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume()}
function tone(freq,duration=.09,type="sine",volume=.045,delay=0){
  if(!soundOn)return;ensureAudio();
  const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();
  o.type=type;o.frequency.setValueAtTime(freq,t);
  g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+duration);
  o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+duration+.03);
}
function sfx(name){
  if(!soundOn)return;
  if(name==="click"){tone(520,.07,"sine",.026);tone(690,.06,"sine",.018,.045)}
  if(name==="sweet"){tone(523,.14,"sine",.035);tone(659,.16,"sine",.03,.08);tone(784,.22,"sine",.028,.17)}
  if(name==="wrong"){tone(260,.10,"triangle",.035);tone(190,.14,"triangle",.03,.08)}
  if(name==="quiz"){tone(440,.08,"sine",.025);tone(554,.10,"sine",.022,.055)}
  if(name==="yes"){[523,659,784,1047].forEach((f,i)=>tone(f,.22,"sine",.045,i*.09))}
}
function showSoundNote(msg){const n=document.createElement("div");n.className="sound-note";n.textContent=msg;document.body.appendChild(n);setTimeout(()=>n.remove(),2200)}
soundToggle.addEventListener("click",e=>{e.stopPropagation();ensureAudio();soundOn=!soundOn;soundToggle.textContent=soundOn?"🔊 Sound On":"🔇 Sound Off";soundToggle.classList.toggle("off",!soundOn);if(soundOn){sfx("sweet");showSoundNote("Love sounds on ❤️")}else showSoundNote("Sounds muted")});
document.addEventListener("pointerdown",e=>{if(!e.target.closest("#soundToggle"))ensureAudio()},{once:true});
document.addEventListener("click",e=>{if(e.target.closest("a,.btn,.dot,.answer-btn,.modal-close")&&!e.target.closest("#soundToggle"))sfx("click")});

const slides=[...document.querySelectorAll(".slide")],dots=[...document.querySelectorAll(".dot")];let current=0;function showSlide(i){slides.forEach((s,n)=>s.classList.toggle("active",n===i));dots.forEach((d,n)=>d.classList.toggle("active",n===i));current=i}dots.forEach(d=>d.addEventListener("click",()=>showSlide(+d.dataset.slide)));setInterval(()=>showSlide((current+1)%slides.length),5500);
const hearts=document.getElementById("hearts");setInterval(()=>{const h=document.createElement("div");h.className="floating-heart";h.textContent=Math.random()>.35?"❤":"♡";h.style.left=Math.random()*100+"vw";h.style.fontSize=12+Math.random()*25+"px";h.style.animationDuration=6+Math.random()*7+"s";hearts.appendChild(h);setTimeout(()=>h.remove(),14000)},450);
const modal=document.getElementById("loveModal"),modalTitle=document.getElementById("modalTitle"),modalText=document.getElementById("modalText");const surprises=["You are my favourite notification. 📱❤️","I still smile when I think of you. That's your fault. 😌","Plot twist: this whole website is just an excuse to say I love you.","No refunds. You're stuck with Milan now. 😂❤️"];document.getElementById("surpriseBtn").onclick=()=>{sfx("sweet");modalTitle.textContent="For Khushi 💗";modalText.textContent=surprises[Math.floor(Math.random()*surprises.length)];modal.classList.add("show")};document.getElementById("modalClose").onclick=()=>modal.classList.remove("show");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("show")};
const quiz=[{q:"Who is the cutest person in this relationship?",a:["Khushi 😌","Milan 😎"],reply:["Correct. Finally, science agrees. 😂","Very confident answer… Milan appreciates the support. 😏"]},{q:"Who gets more dramatic?",a:["Definitely Milan 🎭","Obviously Khushi 👑"],reply:["Excuse me? This website may file an appeal. 😂","Accepted without further investigation. 😌"]},{q:"If we fight, who should say sorry first?",a:["Milan 😇","The one who is wrong 😏"],reply:["Suspiciously convenient answer, Khushi. 😂","Smart answer. Relationship lawyer approved. ✅"]},{q:"Best plan for a perfect evening?",a:["Long drive + food 🚗","Just sit together and talk 🌙"],reply:["Okay, this date is officially noted. ❤️","Simple, peaceful, and somehow my favourite too. ❤️"]}];let qi=0;const qText=document.getElementById("questionText"),answers=document.getElementById("answers"),resp=document.getElementById("quizResponse"),count=document.getElementById("questionCount");function renderQ(){const item=quiz[qi];count.textContent=`Question ${qi+1} of ${quiz.length}`;qText.textContent=item.q;resp.textContent="";answers.innerHTML="";item.a.forEach((x,i)=>{const b=document.createElement("button");b.className="answer-btn";b.textContent=x;b.onclick=()=>{sfx("quiz");resp.textContent=item.reply[i];setTimeout(()=>{qi++;if(qi<quiz.length)renderQ();else{count.textContent="Result 💘";qText.textContent="Diagnosis: Extremely compatible with Milan.";answers.innerHTML='<button class="answer-btn" onclick="document.querySelector(\'#proposal\').scrollIntoView({behavior:\'smooth\'})">See the final question 💍</button>';resp.textContent="Treatment: unlimited hugs, food and patience. 😂❤️"}},1200)};answers.appendChild(b)})}renderQ();
const noBtn=document.getElementById("noBtn"),proposalArea=document.getElementById("proposalArea"),noHint=document.getElementById("noHint");let escapes=0;function moveNo(){const rect=proposalArea.getBoundingClientRect(),br=noBtn.getBoundingClientRect();const maxX=Math.max(0,rect.width-br.width-8),maxY=Math.max(0,rect.height-br.height-8);noBtn.style.left=Math.random()*maxX+"px";noBtn.style.top=Math.random()*maxY+"px";escapes++;const hints=["Arre? 😏","Wrong button 😂","Nice try, Khushi!","No button is shy 🙈","It refuses to cooperate 😌","Okay okay… choose the other one ❤️"];noHint.textContent=hints[Math.min(escapes-1,hints.length-1)]}["mouseenter","touchstart","pointerdown"].forEach(ev=>noBtn.addEventListener(ev,e=>{e.preventDefault();sfx("wrong");moveNo()}));
document.getElementById("yesBtn").onclick=()=>{sfx("yes");modalTitle.textContent="YAAAAAY! 💍❤️";modalText.textContent="Best answer ever. Screenshot this before Milan starts celebrating. 🥹✨";modal.classList.add("show");confettiBurst();for(let i=0;i<18;i++)setTimeout(kissPop,i*55)};
function kissPop(){const k=document.createElement("div");k.className="kiss";k.textContent=Math.random()>.5?"💋":"❤️";k.style.left=20+Math.random()*60+"vw";k.style.top=45+Math.random()*35+"vh";document.body.appendChild(k);setTimeout(()=>k.remove(),1300)}
const canvas=document.getElementById("confetti"),ctx=canvas.getContext("2d");let pieces=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight}addEventListener("resize",resize);resize();function confettiBurst(){pieces=Array.from({length:150},()=>({x:innerWidth/2,y:innerHeight*.45,vx:(Math.random()-.5)*12,vy:-4-Math.random()*9,g:.18+Math.random()*.12,s:4+Math.random()*7,r:Math.random()*6.28}));requestAnimationFrame(draw)}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);pieces.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=p.g;p.r+=.1;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.r);ctx.fillStyle=["#ff477e","#ffd166","#ffffff","#ff85a1"][Math.floor(Math.random()*4)];ctx.fillRect(-p.s/2,-p.s/2,p.s,p.s);ctx.restore()});pieces=pieces.filter(p=>p.y<innerHeight+30);if(pieces.length)requestAnimationFrame(draw);else ctx.clearRect(0,0,canvas.width,canvas.height)}